package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

filegroup(
    name = "typedef_testdata",
    srcs = glob([
        "*.yaml",
        "*.txtproto",
        "*.baseline",
    ]),
)

exports_files(
    srcs = glob([
        "*.yaml",
        "*.txtproto",
        "*.baseline",
    ]),
)
